"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['yys.py']                # 你的主程序文件名
DATA_FILES = []                   # 如果需要额外资源文件，写在这里
OPTIONS = {
    'argv_emulation': True,
    'packages': ['pynput'],               # 如果有隐式导入的库，可以写在这里
    'plist': {
        'CFBundleName': '我的应用',
        'CFBundleShortVersionString': '1.0.0',
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)